import { TimelineTask, BoardCard } from './types';

export const mockTimelineTasks: TimelineTask[] = [
  {
    id: 'task-1',
    name: 'Form 1.0',
    module: 'KK 1.0',
    startDate: new Date('2025-09-01'),
    endDate: new Date('2025-09-15'),
    progress: 100,
    color: '#22c55e',
    status: 'completed',
    assignee: 'John Doe',
  },
  {
    id: 'task-2',
    name: 'KK 1.0',
    module: 'KK 1.0',
    startDate: new Date('2025-09-05'),
    endDate: new Date('2025-09-18'),
    progress: 85,
    color: '#3b82f6',
    status: 'in-progress',
    assignee: 'Jane Smith',
  },
  {
    id: 'task-3',
    name: 'KK 2.0',
    module: 'KK 2.0',
    startDate: new Date('2025-09-12'),
    endDate: new Date('2025-09-25'),
    progress: 60,
    color: '#ef4444',
    status: 'in-progress',
    assignee: 'Bob Wilson',
  },
  {
    id: 'task-4',
    name: 'KK 3.0',
    module: 'KK 3.0',
    startDate: new Date('2025-09-18'),
    endDate: new Date('2025-10-02'),
    progress: 45,
    color: '#f87171',
    status: 'in-progress',
    assignee: 'Alice Brown',
  },
  {
    id: 'task-5',
    name: 'KK 4.0',
    module: 'KK 4.0',
    startDate: new Date('2025-09-22'),
    endDate: new Date('2025-10-10'),
    progress: 30,
    color: '#22c55e',
    status: 'in-progress',
    assignee: 'Charlie Davis',
  },
  {
    id: 'task-6',
    name: 'KK 5.0',
    module: 'KK 5.0',
    startDate: new Date('2025-09-28'),
    endDate: new Date('2025-10-15'),
    progress: 15,
    color: '#06b6d4',
    status: 'pending',
    assignee: 'Diana Evans',
  },
];

export const mockBoardCards: BoardCard[] = [
  {
    id: 'card-1',
    title: 'Review Form 1.0 Data',
    module: 'KK 1.0',
    status: 'completed',
    priority: 'high',
    dueDate: new Date('2025-09-15'),
    assignee: 'John Doe',
  },
  {
    id: 'card-2',
    title: 'Complete KK 1.0 Analysis',
    module: 'KK 1.0',
    status: 'in-progress',
    priority: 'high',
    dueDate: new Date('2025-09-18'),
    assignee: 'Jane Smith',
  },
  {
    id: 'card-3',
    title: 'Start KK 2.0 Documentation',
    module: 'KK 2.0',
    status: 'in-progress',
    priority: 'medium',
    dueDate: new Date('2025-09-25'),
    assignee: 'Bob Wilson',
  },
  {
    id: 'card-4',
    title: 'Prepare KK 3.0 Report',
    module: 'KK 3.0',
    status: 'pending',
    priority: 'medium',
    dueDate: new Date('2025-10-02'),
    assignee: 'Alice Brown',
  },
  {
    id: 'card-5',
    title: 'Initialize KK 4.0 Setup',
    module: 'KK 4.0',
    status: 'pending',
    priority: 'low',
    dueDate: new Date('2025-10-10'),
    assignee: 'Charlie Davis',
  },
  {
    id: 'card-6',
    title: 'Plan KK 5.0 Timeline',
    module: 'KK 5.0',
    status: 'pending',
    priority: 'low',
    dueDate: new Date('2025-10-15'),
    assignee: 'Diana Evans',
  },
];

export const modules = ['All Module', 'Form 1.0', 'KK 1.0', 'KK 2.0', 'KK 3.0', 'KK 4.0', 'KK 5.0'];
export const milestoneTypes = ['All Types', 'Planning', 'Execution', 'Review', 'Completion'];
