export const kk40Data = {
	stats: [
		{
			icon: "warning",
			label: "Total Temuan",
			value: "20",
			description: "Semua temuan QC",
		},
		{
			icon: "progress",
			label: "Open Issue",
			value: "3",
			description: "tidak lengkap",
		},
		{
			icon: "security",
			label: "Closed Issue",
			value: "10",
			description: "Dokument terpenuhi",
		},
	],
	severityDistribution: {
		title: "Distribusi Severity Temuan",
		data: [
			{ name: "Low", value: 20, fill: "#34C759" },
			{ name: "Medium", value: 4, fill: "#FF8D28" },
			{ name: "High", value: 5, fill: "#FF383C" },
		],
	},
	equalisasiChart: {
		title: "Equalisasi SPT vs Laporan (dalam Juta)",
		data: [
			{ category: "Pendapatan", spt: 92, laporan: 43 },
			{ category: "Biaya", spt: 61, laporan: 44 },
			{ category: "Aset", spt: 85, laporan: 53 },
			{ category: "Kewajiban", spt: 27, laporan: 66 },
			{ category: "Next", spt: 30, laporan: 76 },
			{ category: "Next", spt: 72, laporan: 100 },
		],
	},
	findings: [
		{
			id: "1",
			task: "Upload bukti transaksi bulan desember",
			module: "Form 1.0",
			assignee: {
				name: "Karsara",
				initials: "KR",
			},
			priority: "Medium",
			status: "Selesai",
			progress: 75.5,
			due: "2024-10-10",
			daysOverdue: 2,
			updated: "2024-10-10",
		},
		{
			id: "2",
			task: "Upload bukti transaksi bulan desember",
			module: "KK 1.0",
			assignee: {
				name: "Karsara",
				initials: "KR",
			},
			priority: "High",
			status: "In Progress",
			progress: 75.5,
			due: "2024-10-10",
			daysOverdue: null,
			updated: "2024-10-10",
		},
		{
			id: "3",
			task: "Upload bukti transaksi bulan desember",
			module: "KK 1.0",
			assignee: {
				name: "Karsara",
				initials: "KR",
			},
			priority: "Medium",
			status: "In Review",
			progress: 75.5,
			due: "2024-10-10",
			daysOverdue: null,
			updated: "2024-10-10",
		},
		{
			id: "4",
			task: "Upload bukti transaksi bulan desember",
			module: "KK 1.0",
			assignee: {
				name: "Karsara",
				initials: "KR",
			},
			priority: "Low",
			status: "In Progress",
			progress: 75.5,
			due: "2024-10-10",
			daysOverdue: 2,
			updated: "2024-10-10",
		},
		{
			id: "5",
			task: "Upload bukti transaksi bulan desember",
			module: "KK 1.0",
			assignee: {
				name: "Karsara",
				initials: "KR",
			},
			priority: "Medium",
			status: "In Progress",
			progress: 75.5,
			due: "2024-10-10",
			daysOverdue: null,
			updated: "2024-10-10",
		},
	],
};
